function debug(){
	appearmsg("Let's debug the plateform",'Debug')
	setTimeout("localStorage.removeItem('erreur')",1000)
	setTimeout("appearmsg('Checking data','Debug')", 2000)
	setTimeout("appearmsg('Refreshing the system','Debug')", 3000)
	setTimeout("refresh()", 4000)
	setTimeout("appearmsg('Opening a window with text','Debug')", 7000)
	setTimeout("appear('Test window','Test debug')", 8000)
	setTimeout("closetowel()", 9000)
	setTimeout("appearmsg('Simulating a research','Debug')", 10000)
	setTimeout("closetowelmsg()", 11000)
	setTimeout("document.getElementById('link-txt').value='TEST'", 12000)
	setTimeout("linker()", 12500)
	setTimeout("reset()", 13000)
	setTimeout("appearmsg('Removing historic','Debug')", 14000)
	setTimeout("localStorage.removeItem('historic')", 14500)
	setTimeout("appearmsg('Creating historic','Debug')", 15000)
	setTimeout("localStorage.setItem('historic', 'a;b;c;d;e;f;g')", 15500)
	setTimeout("appearmsg('Display historic','Debug')", 16000)
	setTimeout("historic()", 16500)
	setTimeout("appearmsg('Simulating an error','Debug')", 17000)
	setTimeout("faf()", 18000)
	setTimeout("appearmsg('Testing forgetme','Debug')", 20000)
	setTimeout("closetowelmsg();forgetme();", 21000)
	setTimeout("document.getElementById('w1').value='test'", 22000)
	setTimeout("document.getElementById('w2').value='test1'", 22500)
	setTimeout("erasedata();", 23000)
	setTimeout("closetowel()", 24000)
	setTimeout("appearmsg('Testing config','Debug')", 25000)
	setTimeout("config()", 26000)
	setTimeout("appearmsg('Testing slide','Debug')", 27000)
	setTimeout("closeslide()", 27000)
	setTimeout("settingsslide()", 28000)
	setTimeout("appearmsg('Test shortcut','Debug')", 29000)
	setTimeout("shortcut()", 29500)
	setTimeout("appearmsg('Ending...','Debug')", 30700)
	setTimeout("localStorage.removeItem('historic')", 31000)
	setTimeout("closetowelmsg()", 31000)
	setTimeout("error()", 31000)
}
function error(){
	status("System is working. Errors: "+localStorage.getItem('erreur'))
}